# 2024-12-29

name: Pipeline p1.yml

on:
  push:
  workflow_dispatch:  # we can also run it manually


jobs:
  j1:
    # runs-on: ubuntu-latest
    # uses: SV-ICA/rP/.github/workflows/p1.yml@main
    uses: SV-ICA/rP/.github/workflows/pipeline.yml@main
    # uses: SV-ICA/rP/.github/workflows/p1.yml@tag1
    secrets: inherit
